# Для работы CI/CD необходимо заполнить этот файл
# include: можно переиспользовать .setup_venv.yml из модуля про практики DevOps 

#default:
#  tags: [k8s] # Тег для запуска ранера
#  image: python:3.12-bookworm # Образ контейнера, используемого в раннерах

# stages: # Подумай, какие стадии должны быть (линтеры, тесты, билд образа)

# lint: - ruff как линтер и форматер \ mypy для строгой проверки типов

# test: - pytest отличный вариант для unit тестирования

# build: kaniko считается deprecated, попробуй buildkit